package BasicJava;

public class Randomnumber {
public static void main(String[] args) {
	//generated by Math. random() method
	
	for (int i = 0; i < 10; i++) {
		int randomNo = (int) (Math.random () * 100);
		System.out.println(randomNo);
	}
}
}	
	
	
	

